### ISSUE TITLE
WVEMS App Reverts to Old Protocol Version on App Startup

### ISSUE THREAD

**Issue by cneumann01** [MayJuun/wvems_protocols#37]
**Describe the bug**
Protocol version reverts to the old 2021 protocols on iOS/android app startup.

**To Reproduce**
1. Go to App Home Page
2. Click on Settings Gear
3. Click on 2022 WVEMS Protocols
4. Close app/remove from ram
5. Reopen app

**Expected behavior**
Protocol version will revert back to 2021 regardless of what was previously selected. Attempting to remove download for 2021 version results in the error message: 'This PDF was included in the original app, so it cannot be removed.'

**Smartphone (please complete the following information):**
 - Device: [iPhone 14 Pro Max]
 - OS: [iOS16.5.1]
 - Browser [OEM App Store WVEMS App]
 - Version [App. Release v210217]

**Additional context for this error
This bug presents a dangerous situation where some non-techsavy providers believe that outdated procedures are still in their scope of practice. This happens when a user changes the protocol version to the newest one once, and then upon returning to the app sees a particular outdated skill in what they believe to be the updated protocols.

**Comment by FireJuun** [comment]
Addressed in latest app version (v2.1.3). Thanks for the suggestion!
